"use client";
import Link from "next/link";
export default function ServicePlansPromo({ compact = false }: { compact?: boolean }) {
  return <section className={compact ? "servicePromo compact" : "servicePromo"}>
    <div className="serviceGlow" /><div className="serviceCopy"><span className="serviceEyebrow">QR RETURN SERVICE</span><h2>მომსახურება და პაკეტები</h2><p>პროფილის გააქტიურებიდან პირველი <strong>2 თვე უფასოა.</strong> შემდეგ თავად აირჩიე 1-, 3-, 6-თვიანი ან წლიური მომსახურება.</p><div className="serviceBenefits"><span>✓ ფასი იწყება 2 ₾-დან</span><span>✓ რამდენიმე პროდუქტზე ფასდაკლება</span><span>✓ ყველა პროფილი ერთ ანგარიშზე</span></div></div>
    <div className="serviceAction"><div className="pricePreview"><small>წლიური პაკეტი</small><div><b>16 ₾</b><span>-დან</span></div></div><Link href="/account/subscriptions">პაკეტების ნახვა <span>→</span></Link></div>
    <style jsx>{`
      .servicePromo{position:relative;isolation:isolate;overflow:hidden;width:calc(100% - 32px);max-width:1180px;margin:24px auto;padding:30px 34px;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:32px;border:1px solid rgba(255,255,255,.25);border-radius:24px;background:linear-gradient(125deg,#083b72 0%,#0754a1 52%,#1266e9 100%);color:#fff;box-shadow:0 22px 55px rgba(0,25,60,.25)}.serviceGlow{position:absolute;z-index:-1;width:340px;height:340px;right:-100px;top:-170px;border-radius:50%;background:rgba(113,193,255,.24)}.serviceEyebrow{color:#9fd4ff;font-size:12px;font-weight:950;letter-spacing:.14em}.serviceCopy h2{margin:7px 0 9px;font-size:clamp(25px,3vw,36px);line-height:1.15}.serviceCopy p{max-width:720px;margin:0;color:#d8edff;font-size:16px;line-height:1.6}.serviceCopy p strong{color:#fff}.serviceBenefits{margin-top:17px;display:flex;flex-wrap:wrap;gap:9px}.serviceBenefits span{padding:8px 11px;border:1px solid rgba(255,255,255,.19);border-radius:999px;background:rgba(255,255,255,.09);font-size:12px;font-weight:800}.serviceAction{min-width:220px;padding:19px;border:1px solid rgba(255,255,255,.2);border-radius:18px;background:rgba(255,255,255,.11)}.pricePreview small{color:#bfe1ff;font-size:12px}.pricePreview div{margin-top:2px;display:flex;align-items:baseline;gap:5px}.pricePreview b{font-size:31px}.pricePreview span{font-size:13px}.serviceAction a{min-height:48px;margin-top:15px;padding:0 16px;display:flex;align-items:center;justify-content:space-between;border-radius:11px;background:#fff;color:#0647c8;text-decoration:none;font-size:14px;font-weight:950}.serviceAction a span{font-size:20px}.compact{margin-top:18px;margin-bottom:28px}.compact .serviceCopy h2{font-size:28px}@media(max-width:720px){.servicePromo{width:calc(100% - 20px);padding:23px 18px;grid-template-columns:1fr;gap:19px;border-radius:19px}.serviceCopy p{font-size:15px}.serviceBenefits{display:grid}.serviceAction{min-width:0}.compact{margin-top:12px}}
    `}</style>
  </section>;
}
