"use client";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@supabase/supabase-js";

type Profile={tag_code:string;first_name:string|null;last_name:string|null;date_of_birth:string|null;sex:string|null;blood_type:string|null;allergies:string|null;medical_conditions:string|null;medications:string|null;medical_note:string|null;owner_phone:string|null;emergency_contact_name:string|null;emergency_contact_relationship:string|null;emergency_contact_phone:string|null;second_contact_name:string|null;second_contact_relationship:string|null;second_contact_phone:string|null;live_chat_enabled:boolean;location_sharing_enabled:boolean;missing_mode:boolean;missing_message:string|null;active:boolean};

function getClient(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL;const k=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_KEY;return u&&k?createClient(u,k):null}
const mask=(v:string)=>`••••${v.slice(-4)}`;

export default function EmergencyPage(){
 const params=useParams();const tag=typeof params?.tag_code==="string"?decodeURIComponent(params.tag_code).trim().toUpperCase():"";
 const [p,setP]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{async function load(){const s=getClient();if(!s){setError("კავშირი არ არის კონფიგურირებული.");setLoading(false);return}const{data,error:e}=await s.from("emergency_public_profiles").select("*").ilike("tag_code",tag).eq("active",true).maybeSingle();if(e||!data)setError("Emergency პროფილი ვერ მოიძებნა.");else setP(data as Profile);setLoading(false)}void load()},[tag]);
 if(loading)return <main className="state">Emergency პროფილი იტვირთება...</main>;
 if(!p)return <main className="state"><div><b>QR RETURN</b><h1>პროფილი ვერ მოიძებნა</h1><p>{error}</p><a href="/">მთავარ გვერდზე დაბრუნება</a></div></main>;
 const name=[p.first_name,p.last_name].filter(Boolean).join(" ")||"Emergency Profile";
 const values=[["სისხლის ჯგუფი",p.blood_type,true],["ალერგიები",p.allergies,true],["დაავადებები / მდგომარეობები",p.medical_conditions,false],["მედიკამენტები",p.medications,false],["სამედიცინო შენიშვნა",p.medical_note,false],["დაბადების თარიღი",p.date_of_birth,false],["სქესი",p.sex,false]] as const;
 return <main className="page">
  <header className="top"><a href="/" className="brand"><span>QR</span><strong>QR RETURN</strong></a><em>VERIFIED EMERGENCY PROFILE</em></header>
  {p.missing_mode&&<section className="missing"><b>⚠ MISSING PERSON</b><p>{p.missing_message||"გთხოვთ დაუყოვნებლივ დაუკავშირდეთ საკონტაქტო პირს."}</p></section>}
  <section className="hero"><div className="cross">+</div><div><small>EMERGENCY BRACELET</small><h1>{name}</h1><p>სამედიცინო და საკონტაქტო ინფორმაცია გადაუდებელი დახმარებისთვის.</p></div></section>
  <section className="card critical"><small>CRITICAL MEDICAL INFORMATION</small><h2>მნიშვნელოვანი ინფორმაცია</h2><div className="grid">{values.filter(([,v])=>v).map(([l,v,a])=><Info key={l} label={l} value={v!} alert={a}/>)}</div></section>
  <section className="card"><small>EMERGENCY CONTACTS</small><h2>დაუკავშირდით ახლავე</h2><div className="contacts">
   {p.owner_phone&&<Contact title="მფლობელი / პროფილის მმართველი" name="" phone={p.owner_phone}/>}
   {p.emergency_contact_phone&&<Contact title={p.emergency_contact_relationship||"Emergency Contact"} name={p.emergency_contact_name||""} phone={p.emergency_contact_phone}/>}
   {p.second_contact_phone&&<Contact title={p.second_contact_relationship||"მეორე კონტაქტი"} name={p.second_contact_name||""} phone={p.second_contact_phone}/>}
  </div>{p.live_chat_enabled&&<a className="chat" href={`/chat/finder/${encodeURIComponent(p.tag_code)}`}>💬 QR RETURN Live Chat →</a>}</section>
  <footer><span>QR CODE</span><strong>{mask(p.tag_code)}</strong><p>სრული QR კოდი საჯაროდ დამალულია.</p></footer>
  <style jsx>{`*{box-sizing:border-box}.page{min-height:100vh;background:#f5f8fc;color:#17324f;padding:0 20px 50px;font-family:Arial,sans-serif}.top{max-width:900px;height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #dbe5f0}.brand{display:flex;align-items:center;gap:9px;text-decoration:none;color:#0747c9}.brand span{width:40px;height:40px;display:grid;place-items:center;border-radius:10px;background:#0747c9;color:white;font-weight:900}.top em,.hero small,.card>small{font-size:10px;font-style:normal;font-weight:900;letter-spacing:1px;color:#0747c9}.missing{max-width:900px;margin:18px auto 0;padding:16px 20px;border-radius:14px;background:#c62828;color:white}.missing p{margin:6px 0 0}.hero{max-width:900px;margin:28px auto 0;padding:28px;display:flex;align-items:center;gap:18px;border-radius:20px;background:#0747c9;color:white}.cross{width:66px;height:66px;display:grid;place-items:center;flex:0 0 66px;border-radius:16px;background:white;color:#0747c9;font-size:46px}.hero small{color:#bcd3ff}.hero h1{margin:5px 0;font-size:34px}.hero p{margin:0;color:#e7efff}.card{max-width:900px;margin:18px auto 0;padding:24px;border:1px solid #dce6f1;border-radius:18px;background:white;box-shadow:0 10px 28px rgba(24,58,95,.06)}.card h2{margin:6px 0 18px}.critical{border-top:5px solid #0747c9}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.contacts{display:grid;gap:11px}.chat{margin-top:14px;min-height:52px;padding:0 16px;display:flex;align-items:center;border-radius:12px;background:#eaf2ff;color:#0747c9;font-weight:900;text-decoration:none}footer{max-width:900px;margin:20px auto 0;text-align:center;color:#789}footer span,footer strong{display:block}footer strong{margin-top:5px;color:#17324f;font-size:18px}footer p{font-size:12px}.state{min-height:100vh;display:grid;place-items:center;text-align:center;background:#f5f8fc;color:#456}.state a{color:#0747c9}@media(max-width:650px){.top em{display:none}.hero{padding:22px}.hero h1{font-size:27px}.grid{grid-template-columns:1fr}}`}</style>
 </main>
}
function Info({label,value,alert=false}:{label:string;value:string;alert?:boolean}){return <div style={{padding:"15px",borderRadius:"12px",background:alert?"#fff3f3":"#f6f9fd",border:alert?"1px solid #f1caca":"1px solid #e2eaf3"}}><small style={{display:"block",color:alert?"#b42318":"#6b7f94",fontWeight:900}}>{label}</small><strong style={{display:"block",marginTop:"6px",fontSize:"16px",color:alert?"#9f1d16":"#17324f"}}>{value}</strong></div>}
function Contact({title,name,phone}:{title:string;name:string;phone:string}){return <a href={`tel:${phone}`} style={{minHeight:"70px",padding:"13px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"15px",borderRadius:"13px",background:"#0747c9",color:"white",textDecoration:"none"}}><span><small style={{display:"block",opacity:.75,fontWeight:800}}>{title}</small><strong style={{display:"block",marginTop:"4px"}}>{name||phone}</strong>{name&&<em style={{display:"block",marginTop:"3px",fontStyle:"normal",opacity:.9}}>{phone}</em>}</span><b style={{fontSize:"22px"}}>☎</b></a>}
