"use client";

import Link from "next/link";

const sections = [
  ["რა ინფორმაციას ვამუშავებთ", "QR RETURN ამუშავებს მხოლოდ იმ მონაცემებს, რომლებიც საჭიროა ანგარიშის, QR პროფილის, შეკვეთის, მხარდაჭერისა და დაბრუნების ფუნქციებისათვის."],
  ["საჯარო QR პროფილი", "მფლობელი თავად ირჩევს, რომელი ინფორმაცია გამოჩნდეს მპოვნელისთვის. სრული Tag Code საჯაროდ არ ჩანს."],
  ["ლოკაცია", "ლოკაცია ავტომატურად არ იგზავნება. მფლობელიც და მპოვნელიც მას მხოლოდ საკუთარი სურვილითა და მოწყობილობის ნებართვით აზიარებენ."],
  ["კომუნიკაცია", "Live Chat-ისა და Support-ის შეტყობინებები გამოიყენება მპოვნელის, მფლობელისა და QR RETURN მხარდაჭერის დასაკავშირებლად."],
  ["თქვენი კონტროლი", "ანგარიშიდან შეგიძლიათ QR პროფილის მონაცემების, ხილვადობისა და დაკავშირების მეთოდების შეცვლა."],
];

export default function PrivacyPage(){return <main><header><Link href="/">QR RETURN</Link><Link href="/">← მთავარ გვერდზე</Link></header><section className="hero"><span>QR RETURN · PRIVACY</span><h1>კონფიდენციალურობა</h1><p>თქვენი ინფორმაცია უნდა გამოჩნდეს მხოლოდ თქვენი არჩევანის შესაბამისად.</p></section><section className="content"><p className="updated">განახლებულია: 28 აგვისტო, 2026</p>{sections.map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}<div className="contact"><h2>კითხვა გაქვთ?</h2><p>კონფიდენციალურობასთან დაკავშირებული საკითხისთვის მოგვწერეთ QR RETURN Support-ში.</p><Link href="/support">Support-ის გახსნა →</Link></div></section><style jsx>{`*{box-sizing:border-box}main{min-height:100vh;background:#fff;color:#172b43}header{width:calc(100% - 32px);max-width:1100px;min-height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between}header :global(a){color:#1266e9;font-size:12px;font-weight:900;text-decoration:none}.hero{padding:80px 24px;background:#1266e9;color:#fff;text-align:center}.hero span{font-size:10px;font-weight:900;letter-spacing:1.4px}.hero h1{margin:12px 0 0;font-size:clamp(38px,6vw,62px)}.hero p{margin:15px auto 0;max-width:650px;color:#ffffffc7;font-size:15px}.content{width:calc(100% - 32px);max-width:900px;margin:auto;padding:55px 0 90px}.updated{color:#7c8da2;font-size:11px}article{display:grid;grid-template-columns:45px 1fr;gap:18px;padding:28px 0;border-bottom:1px solid #e0e8f2}article>span{color:#1266e9;font-size:11px;font-weight:900}h2{margin:0;font-size:22px}article p,.contact p{color:#657990;font-size:14px;line-height:1.75}.contact{margin-top:42px;padding:28px;border-radius:18px;background:#1266e9;color:#fff}.contact p{color:#ffffffc4}.contact :global(a){color:#fff;font-size:12px;font-weight:900;text-decoration:none}@media(max-width:600px){.hero{padding:60px 18px}article{grid-template-columns:1fr;gap:8px}}`}</style></main>}