import Link from "next/link";

const sections = [
  ["სერვისის დანიშნულება", "QR RETURN არის QR-ზე დაფუძნებული საკომუნიკაციო სისტემა დაკარგული ნივთების, ცხოველებისა და Emergency პროფილებისთვის."],
  ["მომხმარებლის პასუხისმგებლობა", "მომხმარებელი პასუხისმგებელია ანგარიშსა და QR პროფილში შეტანილი ინფორმაციის სისწორეზე და საკუთარ მონაცემებზე წვდომის დაცვაზე."],
  ["QR პროფილის გამოყენება", "QR კოდი უნდა გამოიყენოთ კანონიერად და მხოლოდ შესაბამისი ნივთის, ცხოველის ან პირის თანხმობით შექმნილი Emergency პროფილისთვის."],
  ["Emergency ინფორმაცია", "QR RETURN არ ცვლის პროფესიულ სამედიცინო დახმარებას ან საგანგებო სამსახურს. გადაუდებელ შემთხვევაში დაუკავშირდით შესაბამის სამსახურს."],
  ["შეკვეთები და პროდუქტები", "პროდუქტის ფასი, მარაგი, მიწოდება და დაბრუნების პირობები შეკვეთის დროს ნაჩვენები ინფორმაციის მიხედვით განისაზღვრება."],
  ["სერვისის უსაფრთხოება", "აკრძალულია სისტემის ბოროტად გამოყენება, სხვის ანგარიშზე უნებართვო წვდომა ან შეცდომაში შემყვანი ინფორმაციის განთავსება."],
];

export default function TermsPage(){return <main><header><Link href="/">QR RETURN</Link><Link href="/">← მთავარ გვერდზე</Link></header><section className="hero"><span>QR RETURN · TERMS</span><h1>გამოყენების წესები</h1><p>QR RETURN-ის გამოყენების ძირითადი პირობები.</p></section><section className="content"><p className="updated">განახლებულია: 28 აგვისტო, 2026</p>{sections.map(([title,text],i)=><article key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}<div className="contact"><h2>დახმარება გჭირდებათ?</h2><p>ანგარიშის, QR პროფილის ან შეკვეთის შესახებ მოგვწერეთ Support-ში.</p><Link href="/support">Support-ის გახსნა →</Link></div></section><style jsx>{`*{box-sizing:border-box}main{min-height:100vh;background:#fff;color:#172b43}header{width:calc(100% - 32px);max-width:1100px;min-height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between}header :global(a){color:#1266e9;font-size:12px;font-weight:900;text-decoration:none}.hero{padding:80px 24px;background:#1266e9;color:#fff;text-align:center}.hero span{font-size:10px;font-weight:900;letter-spacing:1.4px}.hero h1{margin:12px 0 0;font-size:clamp(38px,6vw,62px)}.hero p{margin:15px auto 0;max-width:650px;color:#ffffffc7;font-size:15px}.content{width:calc(100% - 32px);max-width:900px;margin:auto;padding:55px 0 90px}.updated{color:#7c8da2;font-size:11px}article{display:grid;grid-template-columns:45px 1fr;gap:18px;padding:28px 0;border-bottom:1px solid #e0e8f2}article>span{color:#1266e9;font-size:11px;font-weight:900}h2{margin:0;font-size:22px}article p,.contact p{color:#657990;font-size:14px;line-height:1.75}.contact{margin-top:42px;padding:28px;border-radius:18px;background:#1266e9;color:#fff}.contact p{color:#ffffffc4}.contact :global(a){color:#fff;font-size:12px;font-weight:900;text-decoration:none}@media(max-width:600px){.hero{padding:60px 18px}article{grid-template-columns:1fr;gap:8px}}`}</style></main>}