"use client";

import { QRIcon, ShieldIcon } from "./HomeIcons";

export default function HomeContinuation({ka}:{ka:boolean}) {
  return <div className="continuation">
    <section className="section privacy sectionBorder">
      <div className="shell privacyInner">
        <div className="privacyIcon"><ShieldIcon /></div>
        <div><span>02 · PRIVACY</span><h2>{ka ? "თქვენი ინფორმაცია — თქვენი არჩევანი." : "Your Information, Your Choice."}</h2><p>{ka ? "საჯარო გვერდზე სრული Tag Code არ ჩანს. მფლობელი თავად ირჩევს ტელეფონის, ელფოსტის, მისამართის, Live Chat-ისა და ლოკაციის ხილვადობას." : "The full Tag Code is not public. The owner controls phone, email, address, Live Chat and location visibility."}</p></div>
        <div className="privacyPoints"><strong>✓ {ka ? "Tag Code დაფარულია" : "Tag Code masked"}</strong><strong>✓ {ka ? "ლოკაცია ნებაყოფლობითია" : "Location is voluntary"}</strong><strong>✓ {ka ? "მონაცემებს მფლობელი მართავს" : "Owner controls data"}</strong></div>
      </div>
    </section>

    <section className="cta sectionBorder"><div className="shell ctaInner"><div className="ctaQr"><QRIcon size={42}/></div><div><span>QR RETURN</span><h2>{ka ? "დაკარგვა არ ნიშნავს დამშვიდობებას." : "Never lose what matters."}</h2><p>{ka ? "ერთი სწორი კავშირი შეიძლება გახდეს დაბრუნების დასაწყისი." : "One right connection can begin the return."}</p></div><div className="ctaButtons"><a href="/store">{ka ? "მაღაზია" : "Store"}</a><a href="/signup">{ka ? "რეგისტრაცია" : "Register"}</a></div></div></section>

    <footer><div className="shell footerTop"><div className="brand"><div><QRIcon size={23}/></div><strong>QR RETURN<small>SMART LOST &amp; FOUND</small></strong></div><p>{ka ? "ნივთების, ცხოველებისა და Emergency პროფილების ერთიანი QR სისტემა." : "One QR system for belongings, pets and Emergency profiles."}</p><nav><a href="/store">{ka ? "მაღაზია" : "Store"}</a><a href="/support">Live Chat</a><a href="/login">{ka ? "შესვლა" : "Sign in"}</a><a href="/signup">{ka ? "რეგისტრაცია" : "Register"}</a></nav></div><div className="shell copyright">© 2026 QR RETURN</div></footer>

    <style jsx>{`
      .continuation{color:#17324d;background:#f4f7fb}.shell{width:calc(100% - 80px);max-width:1280px;margin:auto}.section{padding:92px 0}.sectionBorder{border-top:1px solid #dce4ee}.privacyInner{display:grid;grid-template-columns:100px 1fr .72fr;gap:28px;align-items:center}.privacyIcon{width:86px;height:86px;display:grid;place-items:center;border-radius:20px;background:#1266e9;color:#fff;box-shadow:0 14px 30px rgba(18,102,233,.18)}.privacyIcon :global(svg){width:40px;height:40px}.privacy h2,.cta h2{margin:8px 0 0;color:#17324d;font-size:30px}.privacy p,.cta p{color:#687b8f;font-size:13px;line-height:1.7}.footerTop>p{color:rgba(255,255,255,.7);font-size:11px;line-height:1.7}.privacyPoints{display:grid;gap:9px}.privacyPoints strong{padding:13px 14px;border:1px solid #d8e2ed;border-radius:11px;background:#fff;color:#29445f;font-size:11px;box-shadow:0 8px 20px rgba(31,64,103,.05)}.cta{padding:54px 0;background:#fff}.ctaInner{display:grid;grid-template-columns:70px 1fr auto;gap:22px;align-items:center}.ctaQr{width:62px;height:62px;display:grid;place-items:center;border-radius:16px;background:#1266e9;color:#fff}.cta h2{font-size:26px}.cta p{margin:6px 0 0}.ctaButtons{display:flex;gap:8px}.ctaButtons a{min-height:42px;padding:0 17px;display:flex;align-items:center;border-radius:10px;background:#1266e9;color:#fff;font-size:11px;font-weight:900;text-decoration:none}.ctaButtons a:last-child{border:1px solid #cbd8e7;background:#f7f9fc;color:#1266e9}footer{padding:46px 0 18px;border-top:1px solid rgba(255,255,255,.16);background:#0649ad}.footerTop{display:grid;grid-template-columns:220px 1fr auto;gap:25px;align-items:center}.brand{display:flex;align-items:center;gap:9px}.brand>div{width:40px;height:40px;display:grid;place-items:center;border-radius:10px;background:#fff;color:#0754c7}.brand strong{font-size:13px}.brand small{display:block;margin-top:2px;color:rgba(255,255,255,.6);font-size:6px;letter-spacing:1px}.footerTop nav{display:flex;gap:15px}.footerTop a{color:#fff;font-size:9px;font-weight:800;text-decoration:none}.copyright{margin-top:28px;padding-top:15px;border-top:1px solid rgba(255,255,255,.13);color:rgba(255,255,255,.55);font-size:8px}
      @media(max-width:1050px){.privacyInner{grid-template-columns:86px 1fr}.privacyPoints{grid-column:1/-1;grid-template-columns:repeat(3,1fr)}.footerTop{grid-template-columns:1fr 1fr}.footerTop nav{grid-column:1/-1}}@media(max-width:650px){.shell{width:calc(100% - 28px)}.section{padding:64px 0}.privacyInner{grid-template-columns:1fr}.privacyPoints{grid-template-columns:1fr}.ctaInner{grid-template-columns:60px 1fr}.ctaButtons{grid-column:1/-1}.footerTop{grid-template-columns:1fr}.footerTop nav{grid-column:auto;flex-wrap:wrap}}
    `}</style>
  </div>
}

function SectionTitle({number,label,title,text}:{number:string;label:string;title:string;text:string}){return <div className="title"><span>{number} · {label}</span><div><h2>{title}</h2><p>{text}</p></div><style jsx>{`.title>span{color:rgba(255,255,255,.62);font-size:8px;font-weight:900;letter-spacing:1.2px}.title>div{margin-top:9px;display:flex;align-items:end;justify-content:space-between;gap:30px}.title h2{margin:0;color:#fff;font-size:clamp(30px,3.7vw,48px);letter-spacing:-1.5px}.title p{max-width:420px;margin:0;color:rgba(255,255,255,.74);font-size:12px;line-height:1.65}@media(max-width:650px){.title>div{align-items:flex-start;flex-direction:column;gap:10px}}`}</style></div>}
function StoreIcon(){return <svg viewBox="0 0 24 24" width="26" height="26" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M4 9h16l-1 11H5L4 9Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/></svg>}
function ProfileIcon(){return <svg viewBox="0 0 24 24" width="27" height="27" fill="none" stroke="currentColor" strokeWidth="1.7"><circle cx="12" cy="8" r="4"/><path d="M5 21c.5-5 2.8-7 7-7s6.5 2 7 7"/></svg>}
function ReturnIcon(){return <svg viewBox="0 0 24 24" width="27" height="27" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M4 12a8 8 0 1 0 3-6"/><path d="M4 4v6h6"/></svg>}
