create schema if not exists private;

create table if not exists public.owner_admin_profile_access (
  id bigint generated by default as identity primary key,
  owner_admin_id bigint not null references public.owner_admins(id) on delete cascade,
  owner_id uuid not null references public.owner_accounts(user_id) on delete cascade,
  item_id bigint not null references public.item(id) on delete cascade,
  can_view_profiles boolean not null default true,
  can_edit_profiles boolean not null default false,
  can_manage_lost_mode boolean not null default false,
  can_manage_visibility boolean not null default false,
  can_manage_contacts boolean not null default false,
  can_manage_location boolean not null default false,
  can_manage_additional_contact boolean not null default false,
  can_use_live_chat boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint owner_admin_profile_access_once unique (owner_admin_id, item_id)
);

create index if not exists owner_admin_profile_access_owner_idx
  on public.owner_admin_profile_access(owner_id);
create index if not exists owner_admin_profile_access_item_idx
  on public.owner_admin_profile_access(item_id);

alter table public.owner_admin_profile_access enable row level security;

drop policy if exists "owner manages admin profile access" on public.owner_admin_profile_access;
create policy "owner manages admin profile access"
on public.owner_admin_profile_access
for all
to authenticated
using ((select auth.uid()) = owner_id)
with check (
  (select auth.uid()) = owner_id
  and exists (
    select 1 from public.owner_admins oa
    where oa.id = owner_admin_id and oa.owner_id = (select auth.uid())
  )
  and exists (
    select 1 from public.item i
    where i.id = item_id and i.owner_id = (select auth.uid())
  )
);

drop policy if exists "admin views assigned profile access" on public.owner_admin_profile_access;
create policy "admin views assigned profile access"
on public.owner_admin_profile_access
for select
to authenticated
using (
  exists (
    select 1 from public.owner_admins oa
    where oa.id = owner_admin_id
      and oa.admin_user_id = (select auth.uid())
      and oa.active = true
  )
);

grant select, insert, update, delete on public.owner_admin_profile_access to authenticated;
grant usage, select on sequence public.owner_admin_profile_access_id_seq to authenticated;

create or replace function private.validate_owner_admin_profile_access()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.owner_admins oa
    where oa.id = new.owner_admin_id and oa.owner_id = new.owner_id
  ) then
    raise exception 'Administrator does not belong to this owner.';
  end if;

  if not exists (
    select 1 from public.item i
    where i.id = new.item_id and i.owner_id = new.owner_id
  ) then
    raise exception 'Profile does not belong to this owner.';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists validate_owner_admin_profile_access on public.owner_admin_profile_access;
create trigger validate_owner_admin_profile_access
before insert or update on public.owner_admin_profile_access
for each row execute function private.validate_owner_admin_profile_access();

drop policy if exists "admin can read assigned qr profiles" on public.item;
create policy "admin can read assigned qr profiles"
on public.item
for select
to authenticated
using (
  exists (
    select 1
    from public.owner_admins oa
    join public.owner_admin_profile_access apa on apa.owner_admin_id = oa.id
    where oa.owner_id = item.owner_id
      and oa.admin_user_id = (select auth.uid())
      and oa.active = true
      and oa.can_view_profiles = true
      and apa.item_id = item.id
      and apa.can_view_profiles = true
  )
);

create or replace function private.enforce_secondary_admin_item_permissions()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  permission_row record;
begin
  if auth.uid() is null or auth.uid() = old.owner_id then
    return new;
  end if;

  select
    (oa.can_edit_profiles and apa.can_edit_profiles) as can_edit_profiles,
    (oa.can_manage_lost_mode and apa.can_manage_lost_mode) as can_manage_lost_mode,
    (oa.can_manage_visibility and apa.can_manage_visibility) as can_manage_visibility,
    (oa.can_manage_contacts and apa.can_manage_contacts) as can_manage_contacts,
    (oa.can_manage_location and apa.can_manage_location) as can_manage_location,
    (oa.can_manage_additional_contact and apa.can_manage_additional_contact) as can_manage_additional_contact
  into permission_row
  from public.owner_admins oa
  join public.owner_admin_profile_access apa on apa.owner_admin_id = oa.id
  where oa.owner_id = old.owner_id
    and oa.admin_user_id = auth.uid()
    and oa.active = true
    and apa.item_id = old.id
    and apa.can_view_profiles = true;

  if not found then
    raise exception 'This profile is not assigned to this administrator.';
  end if;

  if new.active is distinct from old.active and not permission_row.can_manage_lost_mode then
    raise exception 'Lost Mode permission denied.';
  end if;

  if (to_jsonb(new) - array['active','phone_enabled','whatsapp_enabled','live_chat_enabled','location_sharing_enabled','additional_contact_name','additional_contact_phone','additional_contact_email','show_additional_contact','show_owner_name','show_owner_phone','show_owner_email','show_owner_address','show_owner_photo','show_photo','show_colour','show_description','show_sex','show_date_of_birth','show_weight','show_medical_info','show_behaviour_note','show_brand','show_model','show_size','show_material','show_distinctive_features','show_finder_message','scan_count','last_scanned_at','last_scan_latitude','last_scan_longitude','last_scan_accuracy']
      is distinct from
      to_jsonb(old) - array['active','phone_enabled','whatsapp_enabled','live_chat_enabled','location_sharing_enabled','additional_contact_name','additional_contact_phone','additional_contact_email','show_additional_contact','show_owner_name','show_owner_phone','show_owner_email','show_owner_address','show_owner_photo','show_photo','show_colour','show_description','show_sex','show_date_of_birth','show_weight','show_medical_info','show_behaviour_note','show_brand','show_model','show_size','show_material','show_distinctive_features','show_finder_message','scan_count','last_scanned_at','last_scan_latitude','last_scan_longitude','last_scan_accuracy'])
    and not permission_row.can_edit_profiles then
    raise exception 'Profile editing permission denied.';
  end if;

  if (new.phone_enabled, new.whatsapp_enabled, new.live_chat_enabled)
      is distinct from (old.phone_enabled, old.whatsapp_enabled, old.live_chat_enabled)
    and not permission_row.can_manage_contacts then
    raise exception 'Contact methods permission denied.';
  end if;

  if new.location_sharing_enabled is distinct from old.location_sharing_enabled
    and not permission_row.can_manage_location then
    raise exception 'Location permission denied.';
  end if;

  if (new.additional_contact_name, new.additional_contact_phone, new.additional_contact_email, new.show_additional_contact)
      is distinct from (old.additional_contact_name, old.additional_contact_phone, old.additional_contact_email, old.show_additional_contact)
    and not permission_row.can_manage_additional_contact then
    raise exception 'Additional contact permission denied.';
  end if;

  if (new.show_owner_name, new.show_owner_phone, new.show_owner_email, new.show_owner_address, new.show_owner_photo,
      new.show_photo, new.show_colour, new.show_description, new.show_sex, new.show_date_of_birth, new.show_weight,
      new.show_medical_info, new.show_behaviour_note, new.show_brand, new.show_model, new.show_size, new.show_material,
      new.show_distinctive_features, new.show_finder_message)
      is distinct from
      (old.show_owner_name, old.show_owner_phone, old.show_owner_email, old.show_owner_address, old.show_owner_photo,
      old.show_photo, old.show_colour, old.show_description, old.show_sex, old.show_date_of_birth, old.show_weight,
      old.show_medical_info, old.show_behaviour_note, old.show_brand, old.show_model, old.show_size, old.show_material,
      old.show_distinctive_features, old.show_finder_message)
    and not permission_row.can_manage_visibility then
    raise exception 'Visibility permission denied.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_secondary_admin_item_permissions on public.item;
create trigger enforce_secondary_admin_item_permissions
before update on public.item
for each row execute function private.enforce_secondary_admin_item_permissions();
