"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";

type RequestRow={id:string;item_id:number;period_months:number;base_amount:number;discount_percent:number;final_amount:number;status:string;requested_at:string;item?:{item_name?:string|null;tag_code?:string|null;item_type?:string|null}|null};

export default function AdminServicesPage(){
 const router=useRouter(); const [rows,setRows]=useState<RequestRow[]>([]); const [loading,setLoading]=useState(true); const [working,setWorking]=useState<string|null>(null); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!admin){throw new Error("ადმინისტრატორის წვდომა აუცილებელია.")}const {data,error}=await supabase.from("service_activation_requests").select("id,item_id,period_months,base_amount,discount_percent,final_amount,status,requested_at,item:item_id(item_name,tag_code,item_type)").order("requested_at",{ascending:false});if(error)throw error;setRows((data||[]) as unknown as RequestRow[])}catch(err){setError(err instanceof Error?err.message:"მოთხოვნების ჩატვირთვა ვერ მოხერხდა.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function confirm(id:string){setWorking(id);setError("");const {error}=await supabase.from("service_activation_requests").update({status:"confirmed"}).eq("id",id).eq("status","pending");if(error)setError(error.message);else await load();setWorking(null)}
 return <main><header><Link href="/admin">← ადმინისტრატორის პანელი</Link><strong>QR RETURN</strong></header><section><div className="heading"><span>მომსახურება</span><h1>პაკეტების გააქტიურების მოთხოვნები</h1><p>დადასტურებისას პროფილის დასრულების თარიღი და მომხმარებლის შეტყობინებები ავტომატურად შეიქმნება.</p></div>{error&&<div className="error">{error}</div>}{loading?<div className="state">იტვირთება...</div>:rows.length?<div className="list">{rows.map(row=><article key={row.id}><div><small>{row.item?.tag_code||`#${row.item_id}`}</small><h2>{row.item?.item_name||"QR პროფილი"}</h2><p>{row.period_months===12?"1 წელი":`${row.period_months} თვე`} · ფასდაკლება {row.discount_percent}%</p></div><div className="price"><small>გადასახდელი</small><b>{row.final_amount} ₾</b></div><span className={`status ${row.status}`}>{row.status==="pending"?"დასადასტურებელი":row.status==="confirmed"?"გააქტიურებული":row.status}</span>{row.status==="pending"&&<button onClick={()=>confirm(row.id)} disabled={working===row.id}>{working===row.id?"აქტიურდება...":"დადასტურება და გააქტიურება"}</button>}</article>)}</div>:<div className="state">ახალი მოთხოვნა ჯერ არ არის.</div>}</section><style jsx global>{`*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#f4f7fb;color:#16324d}main{min-height:100vh}header{min-height:70px;padding:0 max(18px,calc((100% - 1100px)/2));display:flex;align-items:center;justify-content:space-between;background:#073f78;color:#fff}header a{color:#fff;text-decoration:none;font-weight:800;font-size:13px}section{width:calc(100% - 28px);max-width:1100px;margin:34px auto}.heading span{color:#0966db;font-size:12px;font-weight:900}.heading h1{margin:7px 0;font-size:32px}.heading p{margin:0;color:#667b90}.list{margin-top:22px;display:grid;gap:10px}.list article{padding:17px;display:grid;grid-template-columns:1fr 130px 130px auto;align-items:center;gap:14px;border:1px solid #dae5ef;border-radius:16px;background:#fff}.list h2{margin:4px 0;font-size:18px}.list p,.list small{margin:0;color:#6d8194;font-size:12px}.price b,.price small{display:block}.price b{margin-top:3px;font-size:21px}.status{padding:7px 9px;border-radius:999px;background:#eef3f8;text-align:center;font-size:11px;font-weight:900}.status.pending{background:#fff4d8;color:#8b6500}.status.confirmed{background:#e7f8ef;color:#087443}.list button{min-height:42px;padding:0 13px;border:0;border-radius:10px;background:#0966db;color:#fff;font-weight:900;cursor:pointer}.state,.error{margin-top:22px;padding:25px;border-radius:14px;background:#fff;text-align:center}.error{color:#b42318;background:#fff1f0}@media(max-width:700px){.heading h1{font-size:25px}.list article{grid-template-columns:1fr 1fr}.list article>div:first-child{grid-column:1/-1}.list button{grid-column:1/-1}}`}</style></main>
}
